//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovation_Ahead
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CAR
    {
        [Required]
        public string clientName { get; set; }
        [Required]
        public string mobileNo { get; set; }
        public string carName { get; set; }
        public string makeyear { get; set; }
        [Required]
        public string sparePart { get; set; }

        public string filter { get; set; }
    }
}
