//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovation_Ahead
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VehiclesEntities : DbContext
    {
        public VehiclesEntities()
            : base("name=VehiclesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarPart> CarParts { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spLogin(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spLogin", emailParameter, passwordParameter);
        }
    
        public virtual int spnightjob(Nullable<int> softdelete)
        {
            var softdeleteParameter = softdelete.HasValue ?
                new ObjectParameter("softdelete", softdelete) :
                new ObjectParameter("softdelete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spnightjob", softdeleteParameter);
        }
    
        public virtual int spRegister(string email, string password, string mobileNo, string firm)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            var firmParameter = firm != null ?
                new ObjectParameter("firm", firm) :
                new ObjectParameter("firm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRegister", emailParameter, passwordParameter, mobileNoParameter, firmParameter);
        }
    }
}
